	USE backup;

CREATE TABLE IF NOT EXISTS tblbackupjobs (
  JobId BIGINT NOT NULL AUTO_INCREMENT,
  Name CHAR(30) NOT NULL,
  Target CHAR(100) NOT NULL,
  CONSTRAINT idxJobId PRIMARY KEY (JobId)
) ENGINE=MyISAM;
