USE backup;

CREATE TABLE IF NOT EXISTS tblfolders (
  FolderId BIGINT NOT NULL AUTO_INCREMENT,
  Name CHAR(200) NOT NULL,
  Path TEXT NOT NULL,
  CONSTRAINT idxFolderId PRIMARY KEY (FolderId)
) ENGINE=MyISAM;
